import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import EnvBanner from "./components/EnvBanner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// eslint-disable-next-line react-refresh/only-export-components
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Check if production environment variable is set
  const hasProductionEnv = !!process.env.INTERCOM_ACCESS_TOKEN;
  const repositoryUrl = "https://github.com/eddo-ai/intercom-custom-connector";

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <EnvBanner showBanner={!hasProductionEnv} repositoryUrl={repositoryUrl} />
        {children}
      </body>
    </html>
  );
}
